// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "../common/Card";

export interface CardExchangeState { playerExchangeCards: Record<string, boolean>, yourExchangeCards: Array<Card>, }