// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListedGame } from "../common/ListedGame";

export interface GameListResponse { games: Array<ListedGame>, }