// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lobby } from "../common/Lobby";

export interface LobbyDetailsResponse { id: string,  lobby: Lobby, }