// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import {LobbyListResponse} from "./LobbyListResponse";
import {LobbyDetailsResponse} from "./LobbyDetailsResponse";
import {IdResponse} from "./IdResponse";
import {GameListResponse} from "./GameListResponse";
import {GameDetailsResponse} from "./GameDetailsResponse";
import {CardExchangeState} from "../common/CardExchangeState";
import {RoundInProgressState} from "../common/RoundInProgressState";
import {RoundFinishedState} from "../common/RoundFinishedState";
import {ErrorResponse} from "./ErrorResponse";

export type WebSocketResponse = { "type": "lobbyList" } & LobbyListResponse | { "type": "lobbyDetails" } & LobbyDetailsResponse | { "type": "LobbyDeleted" } & IdResponse | { "type": "gameList" } & GameListResponse | { "type": "gameDetailsCardExchange" } & GameDetailsResponse<CardExchangeState> | { "type": "gameDetailsRoundInProgress" } & GameDetailsResponse<RoundInProgressState> | { "type": "gameDetailsCardExchange" } & GameDetailsResponse<RoundFinishedState> | { "type": "gameDeleted" } & IdResponse | { "type": "error" } & ErrorResponse;