// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputCard } from "../common/InputCard";

export interface CardExchangePayload { id: string, cardsToExchange: Array<InputCard>, }