// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardExchangePayload } from "./CardExchangePayload";
import type { ClaimReadinessPayload } from "./ClaimReadinessPayload";
import type { CreateLobbyPayload } from "./CreateLobbyPayload";
import type { IdPayload } from "./IdPayload";
import type { PlaceCardPayload } from "./PlaceCardPayload";

export type WebSocketPayload = { "action": "listLobbies" } | { "action": "getLobbyDetails" } & IdPayload | { "action": "createLobby" } & CreateLobbyPayload | { "action": "joinLobby" } & IdPayload | { "action": "quitLobby" } & IdPayload | { "action": "listGames" } | { "action": "getGameDetails" } & IdPayload | { "action": "cardExchangeMove" } & CardExchangePayload | { "action": "placeCardMove" } & PlaceCardPayload | { "action": "claimReadinessMove" } & ClaimReadinessPayload | { "action": "quitGame" } & IdPayload;