workspace = { members = ["game"] }
[package]
name = "black-widow-core-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
game = {path = "./game"}
serde = { version = "1.0", features = ["derive"] }

