// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardSuit } from "./CardSuit";

export interface Card { suit: CardSuit, value: number, score: number, }