// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { GameSettings } from "./GameSettings";

export interface ObfuscatedGame<S> { settings: GameSettings, players: Array<string>, scores: Record<string, number>, isFinished: boolean, playerDecks: Record<string, number>, yourCards: Array<Card>, state: S, }